mysite/accounts/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/password/$', views.ChangePasswordView.as_view(), name='change_password'),
    url(r'^users/$', views.UsersView.as_view(), name='users'),
    url(r'^users/(?P<pk>(-)?[0-9]+)/$', views.UserView.as_view(), name='user'),
    url(r'^users/(?P<pk>(-)?[0-9]+)/edit/$', views.UserEditView.as_view(), name='user_edit'),
    url(r'^groups/(?P<group_id>[0-9]+)/users/$', views.UsersView.as_view(), name='group_users'),
    url(r'^groups/$', views.GroupsView.as_view(), name='groups'),
    url(r'^groups/(?P<pk>(-)?[0-9]+)/$', views.GroupView.as_view(), name='group'),
]

mysite/main/urls.py
from django.conf.urls import url
# from django.contrib.sitemaps.views import sitemap

from . import views, preblog, feeds  # , sitemaps


urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.Post.as_view(), name='post'),
    # url(r'^page/(?P<pk>[0-9]+)/$', views.Page.as_view(), name='page'),
    url(r'^archive$', views.Archive.as_view(), name='archive'),
    url(r'^authors/(?P<pk>[0-9]+)/$', views.Author.as_view(), name='author'),
]

urlpatterns += [
    url(r'^admin/$', views.AdminIndex.as_view(), name='admin_index'),
    url(r'^admin/meta$', views.AdminBlogMeta.as_view(), name='admin_blog_meta'),
    url(r'^admin/posts$', views.AdminPosts.as_view(), name='admin_posts'),
    url(r'^admin/pages$', views.AdminPosts.as_view(), {'is_blog_page':True}, name='admin_pages'),
    url(r'^admin/post$', views.AdminPost.as_view(), name='admin_post'),
    url(r'^admin/page$', views.AdminPage.as_view(), name='admin_page'),
    url(r'^admin/posts/(?P<pk>[0-9]+)$', views.AdminPost.as_view(), name='admin_edit_post'),
    url(r'^admin/pages/(?P<pk>[0-9]+)$', views.AdminPage.as_view(), name='admin_edit_page'),
    url(r'^admin/posts/delete/(?P<pk>[0-9]+)$', views.DeletePost.as_view(), name='admin_delete_post'),
    url(r'^admin/pages/delete/(?P<pk>[0-9]+)$', views.DeletePage.as_view(), name='admin_delete_page'),
    url(r'^admin/tags/$', views.AdminTags.as_view(), name='admin_tags'),
    url(r'^admin/category/$', views.AdminCategory.as_view(), name='admin_category'),
    url(r'^admin/filter-posts$', views.AdminFilterPosts.as_view(), name='admin_filter_posts'),
    url(r'^admin/tags/delete/(?P<pk>[0-9]+)$', views.simple_delete, {'flag':'tag'}, name='admin_delete_tag'),
    url(r'^admin/categories/delete/(?P<pk>[0-9]+)$', views.simple_delete, {'flag':'category'}, name='admin_delete_category'),
    url(r'^admin/tags/edit/(?P<pk>[0-9]+)$', views.simple_update, {'flag':'tag'}, name='admin_edit_tag'),
    url(r'^admin/categories/edit/(?P<pk>[0-9]+)$', views.simple_update, {'flag':'category'}, name='admin_edit_category'),
]

urlpatterns += [
    url(r'^init$', preblog.BlogInitView.as_view()),
    url(r'^reinit-meta$', preblog.ReInitBlogMetaView.as_view()),
    url(r'^rss/$', feeds.LatestEntriesFeed2(), name='rss'),
    # url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps.sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^admin2/', include(admin.site.urls)),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]

mysite/accounts/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate

def group_values():
    groups = Group.objects.all()
    choices = [(group.id, group.name) for group in groups ]
    return choices

class LoginForm(forms.Form):
    username = forms.CharField(max_length=256)
    password = forms.CharField(max_length=256, widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=256)
    email = forms.EmailField(max_length=256, required=False)
    password = forms.CharField(max_length=256, widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=256, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password != password_confirm:
            raise forms.ValidationError('Two passwords are not the same')

class UserForm(forms.Form):
    username = forms.CharField(max_length=256)
    email = forms.EmailField(max_length=256, required=False)
    # password = forms.CharField(max_length=256, widget=forms.PasswordInput(attrs={'placeholder': 'password'}), required=False)
    # password_confirm = forms.CharField(max_length=256, widget=forms.PasswordInput)
    # is_staff = forms.BooleanField(required=False)
    # is_superuser = forms.BooleanField(required=False)

    # def clean(self):
    #     cleaned_data = super(RegisterForm, self).clean()
    #     password = cleaned_data.get('password')
    #     password_confirm = cleaned_data.get('password_confirm')
    #     if password != password_confirm:
    #         raise forms.ValidationError('Two passwords are not the same')

class UserGroupForm(forms.Form):
    # GROUP_CHOICES = group_values()
    GROUP_CHOICES = ()
    groups = forms.MultipleChoiceField(choices=GROUP_CHOICES, widget=forms.SelectMultiple(attrs={'size':len(GROUP_CHOICES)}))

    def __init__(self, *args, **kwargs):
        super(UserGroupForm, self).__init__(*args, **kwargs)
        groups = [(group.id, group.name) for group in Group.objects.all() ]
        # self.fields['groups'].choices = groups
        # self.fields['groups'].widget = forms.SelectMultiple(attrs={'size':len(groups)})
        self.fields['groups'] = forms.MultipleChoiceField(choices=groups, widget=forms.SelectMultiple(attrs={'size':len(groups)}))

class ProfileForm(forms.Form):
    display_name = forms.CharField(max_length='128')
    biography = forms.CharField(required=False, widget=forms.Textarea)
    homepage = forms.URLField(required=False)
    weixin = forms.URLField(required=False)
    douban = forms.URLField(required=False)
    weibo = forms.URLField(required=False)
    zhihu = forms.URLField(required=False)
    github = forms.URLField(required=False)

class ChangePasswordForm(forms.Form):
    username = forms.CharField(max_length=256, widget=forms.HiddenInput)
    old_password = forms.CharField(max_length=256, widget=forms.PasswordInput)
    new_password = forms.CharField(max_length=256, widget=forms.PasswordInput)
    confirm_password = forms.CharField(max_length=256, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')
        if new_password != confirm_password:
            raise forms.ValidationError('Two passwords are not the same')

        username = cleaned_data.get('username')
        password = cleaned_data.get('old_password')
        user = authenticate(username=username, password=password)
        if user is None:
            raise forms.ValidationError('username and password does not match')


    

mysite/accounts/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import View
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from guardian.decorators import permission_required

from . import forms

PER_PAGE = settings.MY_SITE['PER_PAGE_ADMIN']


class LoginView(View):
    template_name = 'accounts/simple_form.html'
    def get(self, request, form=None):
        data = {}
        if not form:
            form = forms.LoginForm()
        data['form'] = form
        data['title'] = 'Login'
        data['btn_name'] = 'Login'
        return render(request, self.template_name, data)
    def post(self, request, form=None):
        data = {}
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    # Redirect to a success page.
                    url = request.POST.get('next', None)
                    if not url:
                        url = reverse('main:admin_index')
                    return redirect(url)
                else:
                    # Return a 'disabled account' error message
                    msg = 'The user is disabled'
                    messages.add_message(request, messages.WARNING, msg)
                    return self.get(request, form)
            else:
                # Return an 'invalid login' error message.
                msg = 'Invalid login, user does not exist'
                messages.add_message(request, messages.ERROR, msg)
                return self.get(request, form)

        else:
            return self.get(request, form)

class LogoutView(View):
    def get(self, request):
        logout(request)
        msg = 'Succeed to logout'
        url = reverse('accounts:login')
        return redirect(url)

class RegisterView(View):
    template_name = 'accounts/simple_form.html'
    def get(self, request, form=None):
        if not form:
            form = forms.RegisterForm()

        data = {'title':'Register', 'form':form, 'btn_name':'Register'}

        return render(request, self.template_name, data)

    def post(self, request):
        form = forms.RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            user = User.objects.create_user(username, email, password)
            
            user.save()

            msg = 'Successfully Registered'
            messages.add_message(request, messages.SUCCESS, msg)
            url = reverse('accounts:login')
            return redirect(url)

        else:
            return self.get(request, form)

class UsersView(View):
    template_name = 'accounts/users.html'

    @method_decorator(permission_required('main.change_user', accept_global_perms=True))
    def get(self, request, group_id=0):
        data = {}
        
        if group_id:
            group = Group.objects.get(pk=group_id)
            users = group.user_set.all()
            data['group_id'] = int(group_id)
        else:
            users = User.objects.all()
            data['all'] = True

        key = request.GET.get('key')
        if key:
            users = users.filter(username__icontains=key)

        paginator = Paginator(users, PER_PAGE)
        page = request.GET.get('page')
        try:
            users = paginator.page(page)
        except PageNotAnInteger:
            users = paginator.page(1)
        except EmptyPage:
            users = paginator.page(paginator.num_pages)

        groups = Group.objects.all()
        # data = {'users':users, 'groups':groups}
        data['users'] = users
        data['groups'] = groups

        data['allow_search'] = True

        return render(request, self.template_name, data)

class UserView(View):
    template_name = 'accounts/user.html'

    @method_decorator(permission_required('main.change_user', accept_global_perms=True))
    def get(self, request, pk):
        pk = int(pk)
        data = {}
        try:
            user = User.objects.get(pk=pk)
        except User.DoesNotExist:
            raise Http404
        data['user'] = user

        groups = user.groups.all()
        data['groups'] = groups

        # permissions = user.get_all_permissions()
        # data['permissions'] = permissions
        permissions = user.user_permissions.all()
        data['permissions'] = permissions

        return render(request, self.template_name, data)

class GroupView(View):
    template_name = 'accounts/group.html'

    @method_decorator(permission_required('main.change_user', accept_global_perms=True))
    def get(self, request, pk):
        pk = int(pk)
        data = {}
        try:
            group = Group.objects.get(pk=pk)
        except group.DoesNotExist:
            raise Http404
        data['group'] = group

        permissions = group.permissions.all()
        data['permissions'] = permissions

        users = group.user_set.all()
        data['users'] = users

        return render(request, self.template_name, data)

class UserEditView(View):
    template_name = 'accounts/user_edit.html'

    @method_decorator(permission_required('main.change_user', accept_global_perms=True))
    def get(self, request, pk, user_form=None):
        pk = int(pk)
        data = {}
        try:
            user = User.objects.get(pk=pk)
        except User.DoesNotExist:
            raise Http404
        
        data['user_edited'] = user

        user_dict = {'username':user.username, 'email': user.email}
        if not user_form:
            user_form = forms.UserForm(initial=user_dict)
        data['user_form'] = user_form

        groups = user.groups.all()
        user_groups = [group.id for group in groups ]
        group_dict = {'groups':user_groups}
        user_group_form = forms.UserGroupForm(initial=group_dict)
        data['user_group_form'] = user_group_form

        return render(request, self.template_name, data)

    @method_decorator(permission_required('main.change_user', accept_global_perms=True))
    def post(self, request, pk):
        pk = int(pk)
        try:
            user = User.objects.get(pk=pk)
        except User.DoesNotExist:
            raise Http404
        if request.POST.get('user'):
            form = forms.UserForm(request.POST)
            if form.is_valid():
                user.username = form.cleaned_data['username']
                user.email = form.cleaned_data['email']
                if request.user.is_superuser:
                    user.is_superuser = request.POST.get('is_superuser', False)
                    user.is_staff = request.POST.get('is_staff', False)
                user.save()

                url = reverse('accounts:user_edit', args=(pk,))
                msg = 'Succeed to update user details'
                messages.add_message(request, messages.SUCCESS, msg)
                return redirect(url)

            return self.get(request, pk, user_form=form)
        else:
            group_ids = request.POST.getlist('groups')
            # user.groups.add(*group_ids)
            user.groups = group_ids
            # return HttpResponse(group_ids)
            url = reverse('accounts:user_edit', args=(pk,))
            msg = 'Succeed to update user groups'
            messages.add_message(request, messages.SUCCESS, msg)
            return redirect(url)


class GroupsView(View):
    template_name = 'accounts/groups.html'

    @method_decorator(permission_required('main.change_user', accept_global_perms=True))
    def get(self, request):
        groups = Group.objects.all()
        data = {'groups':groups}

        return render(request, self.template_name, data)

class ProfileView(View):
    template_name = 'accounts/settings_profile.html'

    @method_decorator(login_required)
    def get(self, request, form=None):
        data = {}
        form_data = {
            'display_name' : request.user.account.display_name,
            'biography' : request.user.account.biography,
            'homepage' : request.user.account.homepage,
            'weixin' : request.user.account.weixin,
            'douban' : request.user.account.douban,
            'weibo' : request.user.account.weibo,
            'zhihu' : request.user.account.zhihu,
            'github' : request.user.account.github
        }

        if not form:
            form = forms.ProfileForm(initial=form_data)

        data['form'] = form
        data['is_profile'] = True

        return render(request, self.template_name, data)

    @method_decorator(login_required)
    def post(self, request):
        form = forms.ProfileForm(request.POST)
        if form.is_valid():
            account = request.user.account

            account.display_name = form.cleaned_data['display_name']
            account.biography = form.cleaned_data['biography']
            account.homepage = form.cleaned_data['homepage']
            account.weixin = form.cleaned_data['weixin']
            account.douban = form.cleaned_data['douban']
            account.weibo = form.cleaned_data['weibo']
            account.zhihu = form.cleaned_data['zhihu']
            account.github = form.cleaned_data['github']

            account.save()

            msg = 'Succeed to update profile'

mysite/templates/accounts/group.html
{% extends 'admin_base.html' %}

{% block main %}
<div class="row">
  <div class="col-md-9">
    <div class="row">
        <h4>分组详情 &nbsp; 
            <small><a href="#"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a></small>
        </h4>
        <hr>
        <p><label>名称</label>: {{ group.name }}</p>
    </div>
    <div class="row">
        <h4>用户</h4>
        <hr>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>用户名</th>
                    <th>邮箱</th>
                    <th>是否激活</th>
                    <th>上次登陆</th>
                    <th>创建日期</th>
                    <th style="text-align:center">移出该组</th>
                </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr id="user-{{ user.id }}">
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'accounts:user' user.id %}">{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.is_active }}</td>
                    <td>{{ user.last_login|date:"M d, Y" }}</td>
                    <td>{{ user.date_joined|date:"M d, Y" }}</td>
                    <td style="text-align:center">
                        <!-- <a href="{% url 'accounts:user_edit' user.id %}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
                        &nbsp -->
                        <a href="#"  class="remove-user"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span> </a>
                    </td>
                </tr>
                {% empty %}
                <tr><td colspan="7">No user yet</td></tr>
            {% endfor %}     
            </tbody>
        </table>
    </div>
  </div>
    <div class="col-md-2 col-md-offset-1">
    <h4>权限</h4>
    <hr>
    <ul class="list-group">
        {% for permission in permissions %}
            <li class="list-group-item group-list">{{ permission.name }}</li>
        {% empty %}
            <p>无相关权限!</p>
        {% endfor %}
    </ul>
  </div>

</div>
{% endblock %}

mysite/templates/accounts/groups.html
{% extends "admin_base.html" %}
{% block title %}用户组{% endblock %}

{% block main %}

<div class="row">
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>分组名称</th>
                <th>动作</th>
            </tr>
        </thead>
        <tbody>
        {% for group in groups %}
            <tr id="group-{{ group.id }}">
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'accounts:group' group.id %}">{{ group.name }}</td>
                <td>
                    <a href="#"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
                </td>
            </tr>
            {% empty %}
            <tr><td colspan="7">暂无分组</td></tr>
        {% endfor %}     
        </tbody>
    </table>


    <!-- </div> -->
    <!-- <div class="col-md-2">.col-md-2</div> -->
</div>
{% endblock %}

mysite/templates/accounts/login.html
{% extends "admin_base.html" %}

{% block title %}Login{% endblock %}


{% block main %}
{% load bootstrap3 %}
<div class="row">
    <div class="col-xs-6 col-sm-3"></div>
    <div class="col-xs-6 col-sm-6">
        <form method="POST" action="" id='login'>
        {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary" name="login">Login</button>
        </form>
    </div>
    <div class="col-xs-6 col-sm-3"></div>
</div>

{% endblock %}

mysite/templates/accounts/settings_profile.html
{% extends 'admin_base.html' %}

{% block title %}Profile{% endblock %}

{% block main %}
{% load bootstrap3 %}

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <ul class="nav nav-tabs">
            <li role="presentation" {% if is_profile %} class="active" {% endif %}><a href="{% url 'accounts:profile' %}">Profile</a></li>
            <li role="presentation" {% if is_password %} class="active" {% endif %}onkeyup=""><a href="{% url 'accounts:change_password' %}">Password</a></li>
        </ul>
        
        <br>

        <div class="col-md-10 col-md-offset-1">
        <form method="POST" action="">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary" name="submit">submit</button>
        </form>
        </div>

    </div>
</div>
{% endblock %}

mysite/templates/accounts/simple_form.html
{% extends "admin_base.html" %}

{% block title %}{{ title }}{% endblock %}


{% block main %}
{% load bootstrap3 %}
<div class="row">
    <div class="col-xs-6 col-sm-3"></div>
    <div class="col-xs-6 col-sm-6">
        <form method="POST" action="">
        {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary" name="login">
            {% if btn_name %}
                {{ btn_name }}
            {% else %}
                submit
            {% endif %}
            </button>
        </form>
    </div>
    <div class="col-xs-6 col-sm-3"></div>
</div>

{% endblock %}

mysite/templates/accounts/user.html
{% extends 'admin_base.html' %}

{% block main %}
<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <h4>用户详情 &nbsp; 
        <small><a href="{% url 'accounts:user_edit' user.id %}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a></small>
    </h4>
    <hr>
    <p><label>用户名</label>: {{ user.username }}</p>
    <p><label>邮箱:</label> {{ user.email }}</p>
    <p><label>是否激活:</label> {{ user.is_active}} </p>
    <p><label>是否为管理:</label> {{ user.is_staff}} </p>
    <p><label>是否为超级用户:</label> {{ user.is_superuser}} </p>
    <p><label>上次登陆:</label> {{ user.last_login}}</p>
    <p><label>创建日期:</label> {{ user.date_joined }}</p>
  </div>
  <div class="col-md-2">
    <h4>用户组</h4>
    <hr>
    <ul class="list-group">
        {% for group in groups %}
            <li class="list-group-item group-list"><a href='#'>{{ group.name }}</a></li>
        {% empty %}
            <p>No group yet!</p>
        {% endfor %}
    </ul>
  </div>
    <div class="col-md-2">
    <h4>用户权限</h4>
    <hr>
    <ul class="list-group">
        {% for permission in permissions %}
            <li class="list-group-item group-list">{{ permission.name }}</li>
        {% empty %}
            <p>No permission yet!</p>
        {% endfor %}
    </ul>
  </div>

</div>{% endblock %}

mysite/templates/accounts/user_edit.html
{% extends 'admin_base.html' %}
{% block title %} 编辑用户资料 {% endblock %}

{% load bootstrap3 %}

{% block main %}
<div class="row">
    <div class="col-md-6 col-md-offset-1">
        <h3>用户详情</h3>
        <hr>
        <form method="POST" action="">
        {% csrf_token %}
            {% bootstrap_form user_form %}
            {% if user.is_superuser %}
            <div class="checkbox">
                <label>
                  <input type="checkbox" name="is_superuser" {% if user_edited.is_superuser %}checked{% endif %}> 是否为超级用户
                </label>
            </div>
            <div class="checkbox">
                <label>
                  <input type="checkbox" name="is_staff" {% if user_edited.is_staff %}checked{% endif %}> 是否为管理
                </label>
            </div>
            {% endif %}
            <button type="submit" class="btn btn-primary" name="user" value="user">提交</button>
        </form>
    </div>
    <div class="col-md-4">
        <h3>用户组</h3>
        <hr>
        <form method="POST" action="">
        {% csrf_token %}
            {% bootstrap_form user_group_form %}{{groups}}
            <button type="submit" class="btn btn-primary" name="group" value="group">提交</button>
        </form>
    </div>

</div>

{% endblock %}

mysite/templates/accounts/users.html
{% extends "admin_base.html" %}
{% block title %}Users{% endblock %}

{% block main %}
{% load bootstrap3 %}
<div class="row">
    <div class="col-md-10">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>用户名</th>
                <th>邮箱</th>
                <th>是否激活</th>
                <th>上次登陆</th>
                <th>创建日期</th>
                <th>动作</th>
            </tr>
    </thead>
    <tbody>
    {% for user in users %}
        <tr id="user-{{ user.id }}">
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'accounts:user' user.id %}">{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.is_active }}</td>
            <td>{{ user.last_login|date:"M d, Y" }}</td>
            <td>{{ user.date_joined|date:"M d, Y" }}</td>
            <td>
                <a href="{% url 'accounts:user_edit' user.id %}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
                &nbsp
                <a href="#"  class="del-user"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> </a>
            </td>
        </tr>
        {% empty %}
        <tr><td colspan="7">No user yet</td></tr>
    {% endfor %}     
    </tbody>
    </table>

    {% bootstrap_pagination users %}

    </div>
    <div class="col-md-2">
        <!-- <h4>Filter By Group</h4> -->
        <p><strong>分组显示</strong></p>
        <hr>
        <div class="list-group">
          <a href="{% url 'accounts:users' %}" class="list-group-item group-list {% if all %}active{% endif %}">所有用户</a>
          {% for group in groups %}
            <a href="{% url 'accounts:group_users' group.id %}" class="list-group-item group-list {% if group_id == group.id %}active{% endif %}">{{ group.name }}</a>
          {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
$('.del-user').on('click', function (event) {
    // var answer = confirm("Delete post?");
    // return answer;
    var url = $(this).attr('href');

    bootbox.confirm("确认删除用户?", function(result) {
      if(result){
        $.get(url, function(){
            location.reload();
        });
        }

    });
    return false;
  });
</script>
{% endblock %}